macro(add_vulkan_support target)
    if (${CMAKE_SYSTEM_NAME} MATCHES "Windows")
        target_include_directories(${target} PRIVATE $ENV{VK_SDK_PATH}/Include)
        target_link_directories(${target} PRIVATE $ENV{VK_SDK_PATH}/Lib)
        target_compile_definitions(${target} PRIVATE -DVK_USE_PLATFORM_WIN32_KHR)
        target_link_libraries(${target} vulkan-1)
    else()
        target_include_directories(${target} PRIVATE "/usr/local/include")
        target_link_directories(${target} PRIVATE "/usr/local/lib")
        target_link_libraries(${target} libvulkan.dylib)
    endif ()
endmacro()
